=== Cristian-Calderon/XML/repaso.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    targetNamespace="https://elpuig.xeill.net/MP04/XSD" elementFormDefault="qualified">
    <xs:element name="concessionari">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="cotxe" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="model" type="xs:string" />
                            <xs:element name="nou">
                            <xs:complexType>
                                <xs:attribute name="valor" type="xs:string"></xs:attribute>
                            </xs:complexType>
                            </xs:element>
                            <xs:element name="color" type="xs:string" />
                        </xs:sequence>
                        <xs:attribute name="marca" type="xs:string"></xs:attribute>
                    </xs:complexType>
                </xs:element>
                <xs:element name="furgoneta">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="model" type="xs:string"></xs:element>
                            <xs:element name="nou">
                                <xs:complexType>
                                    <xs:attribute name="valor" type="xs:string">
                                    </xs:attribute>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="color" type="xs:string"></xs:element>
                        </xs:sequence>
                        <xs:attribute name="marca" type="xs:string"></xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Cristian-Calderon/XML/repaso.xml
<?xml version="1.0" encoding="UTF-8"?>
<concessionari xmlns="https://elpuig.xeill.net/MP04/XSD" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="https://elpuig.xeill.net/MP04/XSD repaso.xsd">
	<cotxe marca="renault">
		<model>Capture</model>
		<nou valor="si"/>
		<color>Blanc</color>
	</cotxe>
	<cotxe marca="audi">
		<model>A3</model>
		<nou valor="si"/>
		<color>Vermell</color>
	</cotxe>
	<furgoneta marca="seat">
		<model>Ibiza</model>
		<nou valor="si"/>
		<color>Blau</color>
	</furgoneta>
</concessionari>
