=== Cristian-Calderon/XML/DTD/agenda.dtd
<!ELEMENT agenda (contacte*)>
<!ELEMENT contacte (nom, cognom+, tlf, email?, dir)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT cognom (#PCDATA)>
<!ELEMENT tlf (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT dir (carrer, num, cp)>
<!ELEMENT carrer (#PCDATA)>
<!ELEMENT num (#PCDATA)>
<!ELEMENT cp (#PCDATA)>
<!ATTLIST tlf pais CDATA #REQUIRED>

=== Cristian-Calderon/XML/DTD/agenda.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE agenda SYSTEM "agenda.dtd">
<agenda>
    <contacte>
        <nom></nom>
        <cognom></cognom>
        <tlf pais="Argentina"></tlf>
        <email></email>
        <dir>
            <carrer></carrer>
            <num></num>
            <cp></cp>
        </dir>
    </contacte>
</agenda>
